<a href="https://colab.research.google.com/github/DhimanTarafdar/pytorch-autograd-study/blob/main/pytorch_autograd_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider:

1. x = torch.tensor([2.0], requires_grad=True)

   y = x**2 + 3*x + 1

   y.backward()

What is the value inside x.grad?
Explain how PyTorch computed it step-by-step.



2. What happens in this case?

   x = torch.tensor([2.0])

   y = x**2

   y.backward()

 Why does it fail?



In [ ]:
import torch

In [ ]:
x= torch.tensor([2.0],requires_grad=True)
y= x**2+3*x+1
y.backward()

In [ ]:
x

tensor([2.], requires_grad=True)

In [ ]:
y

tensor([11.], grad_fn=<AddBackward0>)

In [ ]:
x.grad

tensor([7.])

In [ ]:
x=torch.tensor([2.0])
y=x**2
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

# Question 1

x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 1
y.backward()

## What is the value of x.grad?

আমরা জানি,

y = x² + 3x + 1

প্রথমে হাতে ডেরিভেটিভ বের করি।

d/dx (x²) = 2x  
d/dx (3x) = 3  
d/dx (1) = 0  

সুতরাং,

dy/dx = 2x + 3

এখন x = 2 বসাই:

dy/dx = 2(2) + 3  
       = 4 + 3  
       = 7

অতএব,

x.grad = tensor([7.])

---

## PyTorch কিভাবে step-by-step হিসাব করলো?

1. requires_grad=True দেওয়ার ফলে PyTorch x কে track করা শুরু করে।
2. y = x**2 + 3*x + 1 করলে একটি computational graph তৈরি হয়।
3. y.backward() কল করলে:
   - প্রথমে dy/dy = 1 ধরা হয়।
   - তারপর chain rule ব্যবহার করে gradient propagate করা হয়।
4. Autograd হিসাব করে dy/dx = 2x + 3।
5. x = 2 বসিয়ে gradient পাওয়া যায় 7।
6. এই মানটি x.grad এ store হয়।

---

# Question 2

x = torch.tensor([2.0])
y = x**2
y.backward()

## What happens here?

এই ক্ষেত্রে error হবে:

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## Why does it fail?

1. এখানে requires_grad=True দেওয়া হয়নি।
2. তাই x gradient track করছে না।
3. ফলে y-ও gradient track করছে না।
4. y এর কোন grad_fn নেই।
5. তাই y.backward() কল করলে PyTorch বলে:
   "এই tensor gradient track করছে না, তাই backward করা যাবে না।"

---

## Summary

Case 1:
requires_grad=True → gradient হিসাব হয় → x.grad = 7

Case 2:
requires_grad=False → computational graph তৈরি হয় না → backward() করলে error